---
name: Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint project
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Lint code base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JAVA: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_XML: true
          VALIDATE_YAML: true

  build:
    needs: lint
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Setup java 17
        uses: actions/setup-java@v2.4.0
        with:
          distribution: adopt-hotspot
          java-version: 17
          cache: maven

      - name: Maven verify
        run: mvn verify k8s:build -B -ff
