---
name: Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Setup java 17
        uses: actions/setup-java@v2.4.0
        with:
          distribution: adopt-hotspot
          java-version: 17
          cache: maven

      - name: Maven verify
        run: mvn verify k8s:build -B -ff
